### ISSUE TITLE
Signals

### ISSUE THREAD

**Issue by rg3915** [rg3915/orcamentos#38]
Rever signals
Testes falham com signals.

**Comment by paulo-romano** [comment]
Eu conheço um pouco de signals rsrs

**Comment by rg3915** [comment]
@paulo-romano meus testes estão falhando com signals porque ele acaba criando o mesmo User mais de uma vez. Veja isso pra mim por favor.

**Comment by paulo-romano** [comment]
@rg3915, vou pegar esse. Por favor, atribua-o para mim.
