### ISSUE TITLE
Ao criar cadastro me retorna um erro

### ISSUE THREAD

**Issue by fchevitarese** [rg3915/orcamentos#67]
Ao tentar me cadastrar, recebo um erro do django na tela. 

IntegrityError at /inscricao/
duplicate key value violates unique constraint "crm_employee_cpf_key"
DETAIL:  Key (cpf)=() already exists.

**Comment by rg3915** [comment]
@fchevitarese Resolvido. Obrigado.

**Comment by fchevitarese** [comment]
;)



*"*
*São os homens que mais me surpreendem na humanidade. Porque perdem a saúde
para juntar dinheiro, depois perdem dinheiro para recuperar a saúde. E por
pensarem ansiosamente no futuro, esquecem do presente de tal forma que
acabam por não viver nem o presente nem o futuro. E vivem como se nunca
fossem morrer e morrem como se nunca tivessem vivido” - Dalai Lama.*
*"*

*Fred Chevitarese - GNU/Linux*
*http://chevitarese.wordpress.com* <http://chevitarese.wordpress.com>



2016-06-22 23:54 GMT-03:00 Regis da Silva <notifications@github.com>:
