### ISSUE TITLE
Concluir orçamento: deve aceitar formato decimal

### ISSUE THREAD

**Issue by rg3915** [rg3915/orcamentos#9]
deve aceitar formato decimal com vírgula.
Ex: 12,01

**Comment by rg3915** [comment]
Ao clicar em Concluir Orçamento.
![img](https://raw.githubusercontent.com/rg3915/orcamentos/master/img/modal_conclude_proposal.png)

**Comment by rafa-so** [comment]
@rg3915 vou ver se consigo arrumar isso daí rs

**Comment by felipefrizzo** [comment]
@rg3915 é só sentar no settings DECIMAL_SEPARATOR = ','.
e no form setar localize=True
exemplo: price = forms.DecimalField(label='Preço', max_digits=20, decimal_places=2, localize=True)

**Comment by rg3915** [comment]
@felipefrizzo o problema é que esse campo está também neste Modal Form, que foi chamado via JS.

**Comment by rg3915** [comment]
Ou seja, no editar form foi resolvido. Mas no Modal ainda não.

**Comment by rg3915** [comment]
[9ae5785](https://github.com/rg3915/orcamentos/commit/9ae5785adbec26dca859150c38f58cfd4266a49d)

* Ainda falta conferir via JS.
